### ISSUE TITLE
Reduce the size of the video on cc.org/licenses

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#1089]
@cablegreen would like the size of the video at the top of https://creativecommons.org/licenses/ to be reduced. 

I'm unable to make this change because this page is one I don't have to permission to edit.

I think the standard Vimeo embed size of width=640 height=480 would be fine

I chatted with @TimidRobot who explained that this page is part of "ccEngine," which is why I don't have access to it.

Ideally all key staff (especially staff members working on comms) would have the ability to edit all pages across the site. I'm not familiar with ccEngine and why some pages are part of it / not available to be edited by me / @victoriaheath / Cable. How would we make pages like this available to be edited by us? (If you'd like, I can submit this as a separate ticket).

**Comment by kgodey** [comment]
@ericsteuer We'd need to move that page to WordPress in order to make it editable by you; it is not part of WordPress at the moment. It is currently part of the old license infrastructure that we are looking to replace this year. The contents of the page are stored directly in the source code, so editing it requires editing the source code of https://github.com/creativecommons/cc.engine

Please do create a separate ticket to move this page to WordPress. If you have additional pages that you'd like moved, please include those as well.

**Comment by hugosolar** [comment]
Video size reduced
<img width="1133" alt="Screen Shot 2020-03-27 at 10 10 52 AM" src="https://user-images.githubusercontent.com/894708/77759298-4440ac00-7013-11ea-8146-20d64d84eda2.png">
