### ISSUE TITLE
Mystery Wordpress post drafts surfacing in "All Posts" view

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#1095]
Starting earlier this week, a ton of (very) old draft posts started showing up in the "All Posts" view in our WordPress. We use this view to queue posts up and work on them collaboratively before they launch, so the inability to quickly see what's in the queue complicates things.

Any idea why this happened? Any idea what a good solution might be? cc @victoriaheath 

<img width="1073" alt="Screen Shot 2020-04-08 at 11 44 35 AM" src="https://user-images.githubusercontent.com/8919762/78821781-e014d500-798e-11ea-8977-b3398ae13451.png">

**Comment by hugosolar** [comment]
My guess with this is there may have been a brute force attack to those old accounts in order to gain access to the WordPress backend but those accounts only have subscriber access which is the lowest privilege set of WordPress so there's nothing to worry about.

### What has been done
- I remove users roles to those accounts in order to restrict any kind of privileges for those users

### Next steps
- @TimidRobot  will investigate if there was an attack (pointer in this ticket creativecommons/tech-support#503)

**Comment by kgodey** [comment]
Closing this since there's a ticket for further investigation.
