### ISSUE TITLE
update automated donor communication templates

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#230]
in civi under adminster / communications / message templates / system workflow

per discussion and googledoc sent via email

thanks!

**Comment by mattl** [comment]
Template concept is here: https://litmus.com/builder/documents/425387/edit

**Comment by mattl** [comment]
Let me know if you're good with the template, and I'll proceed to get these up.

**Comment by rebeccalendl** [comment]
Template is missing the letter format "dear first name," and the footer that details tax receipt info and PS: CC video. Also missing formatted of bolded stmts. And I've tightened up text slightly after seeing it in design, should be shorter.

**Comment by mattl** [comment]
That's the content, not the template. I'm just looking for feedback on the
template, I just quickly pasted some text in to fill it out a bit.

I don't have edit access to the document, but a few notes on names.

Most people, we don't have their name, because they don't need to provide
it when they donate. What do we want as a default there?

Also, we should be using nickname, not first name for this. Someone's legal
name may differ from how we address them significantly.

**Comment by mattl** [comment]
Updated with lorem ipsum.

**Comment by rebeccalendl** [comment]
Closing. Giant Rabbit will tackle.
