### ISSUE TITLE
Free Cultural Works Button

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#244]
## After a freshdesk ticket triggered some discussion on this (by @peterspdx & @sarahpearson ), it was decided that 

The sentence Sarah suggested be added to our /policies page is fine by me, so that's Task 1. 

Task 2 would be to modify the logo in the way you suggest so that it can be downloaded.
## Task 3 would be to create a new page where the logo (however @mattl  ends up modifying it) will live and a link inserted to that page from the downloads or policy page. 

So Mari will take the first task then reassign this to Matt.  Yay!

**Comment by mmoreshead** [comment]
Ugh, copy paste formatting. I never meant to shout there.

**Comment by peterspdx** [comment]
Noting here I prefer the button(s) not be available on our downloads page. It could confuse people into thinking we control the definition. Hence, we were thinking a separate page. If we wanted to, we could note on the /downloads page at the bottom that CC created that button for our deeds, per our /policies page we waive any copyright in the button and we don't assert we own any trademark rights because we don't steward the definition, and if people want to use it go to [this page] where they can download it.
