### ISSUE TITLE
Change url for "search" on front page

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#262]
Under "use & remix" bucket in blue stripe, "search" has the same url as "search by topic" -- shouldn't be the same. "search" should go directly to our search tool: http://search.creativecommons.org/

**Comment by mattl** [comment]
@little-wow Can you share how to do this too? It's not obvious to me how those things change.

**Comment by little-wow** [comment]
I don't know how to change the front page tbqh

**Comment by mattl** [comment]
@ageeroms Can you help us figure it out?

**Comment by ageeroms** [comment]
I have updated the Search link in the blue band on the homepage to go directly to search.creativecommons.org . Is that what you meant @janeatcc ?

**Comment by janeatcc** [comment]
Yup! Thanks. But more importantly, how do we as CC staff update the home page?

**Comment by ageeroms** [comment]
The widget is called "Share your work" and via Appearance > Widgets (https://staging.creativecommons.org/wordpress/wp-admin/widgets.php ), it's in the Below Content (Homepage) area. It's a HTML list, so you may wish to copy all of the HTML before you begin editing and save that somewhere, then make updates and save and test, so that you can revert if needed. I did paste a copy of the original code onto that draft "Kitchen Sink" page, in case any of the classes are accidentally stripped.

**Comment by janeatcc** [comment]
Thanks @ageeroms!

I don't have permissions to edit that page, but I assume @little-wow and @mattl do.

**Comment by mattl** [comment]
Yep. Thanks @ageeroms

**Comment by little-wow** [comment]
I don't have access to the widgets

On Tuesday, June 21, 2016, Matt Lee <notifications@github.com> wrote:

> Closed #262
> <https://github.com/creativecommons/creativecommons.org/issues/262>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/creativecommons.org/issues/262#event-699931518>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGw-Tj9Kn8P7H-sOoxKX8--_cFE8SuODks5qOKeDgaJpZM4I7NB1>
> .
>


-- 
---
Jennie Rose Halperin
Communications Manager
Creative Commons
Invest in an open future. Support Creative Commons today:
http://bit.ly/19IjSKl
