### ISSUE TITLE
Share of non-homepage on facebook doesn't set preview image

### ISSUE THREAD

**Issue by mackh** [creativecommons/creativecommons.org#283]
go to facebook.com
paste the URL https://creativecommons.org/share-your-work/ into the status box
observe lack of preview image 

works for the homepage, need to test if it fails for other urls

**Comment by ageeroms** [comment]
When I share the homepage on Facebook, I get a nice card image:

![screen shot 2016-06-22 at 2 55 22 pm](https://cloud.githubusercontent.com/assets/6674702/16285213/d7c96842-3889-11e6-82e8-242d6bb744be.png)

But when I paste an interior page, e.g. https://creativecommons.org/share-your-work/ , I get no such image. Please ensure that the same image from the homepage is served, if there is not featured image on interior pages.

Likewise author pages have no image when shared on facebook, e.g. https://creativecommons.org/author/jenniecreativecommons-org and I think the same default should be configured.

**Comment by ageeroms** [comment]
@DylanMcCall

**Comment by DylanMcCall** [comment]
This is related to site configuration, so I can't really do anything about it myself. Still, what you need to do is visit this settings page as an admin user:

http://www.creativecommons.org/wp-admin/admin.php?page=wpseo_social#top#facebook

... and under "Default settings" (where it talks about open graph meta data) set the default _Image URL_ to something nice.

That should also fix your issue with author pages. If you had wanted to show the author's image, that would be a bit more complicated because it looks like the Yoast SEO plugin doesn't support that, but we could probably achieve that if need be by filling in a hook somewhere.

**Comment by mattl** [comment]
https://creativecommons.org/wordpress/wp-admin/admin.php?page=wpseo_social#top#facebook

**Comment by kgodey** [comment]
This is solved per Jennie on Slack.
