### ISSUE TITLE
The odd looking search button is back everywhere on mobile...

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#289]
Going to attach screenshots via email

**Comment by mattl** [comment]
@mattl ping

**Comment by robmyers** [comment]
@mattl pong

**Comment by DylanMcCall** [comment]
May you please attach a screenshot or a description of where this problem appears? I'm not seeing weird looking search buttons myself (with Chrome on Android) and Anna isn't available at the moment if you happened to send details to her directly.

**Comment by DylanMcCall** [comment]
Weird rendering for the search text input itself on mobile Safari via Browserstack. This is happening because it has (somewhat ill-advisedly) set type="search", and iOS's Webkit insists on special rendering for search fields. It also has an overly large min-width, which we can fix in the theme.

![screenshot from 2016-07-07 13-18-45](https://cloud.githubusercontent.com/assets/132063/16668332/5c24b2ec-4445-11e6-9bc2-eeebd64af911.png)

Is this perhaps related to what you were seeing?

**Comment by mattl** [comment]
That's not what I was seeing. I'm using Firefox on Android. I'll have another look.

**Comment by mattl** [comment]
And yay for GNOME 3

**Comment by DylanMcCall** [comment]
Yay another crazy person! Yeah, it makes me happy. It's so *quick* :) Okay, I made a pull request for the other issues I noticed anyway and hopefully we can get to the bottom of the search button.
