### ISSUE TITLE
Blog workflow issues

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#354]
Some initial issues I've noticed:

1. In order to make an article the primary featured article, it has to be tagged as "hero" (this is not an issue in itself, but it is not obvious and could possibly be better served with a check box.) Other articles are still tagged as hero, which could create conflicts in the future?
2. Articles on the main page do not seem to be posted in chronological order, and in order to feature an article, other featured articles have to be detagged as featured, which is cumbersome. 
Again, one has to remember to type featured in the tags box, rather than checking a box. The order of posts on the site isn't clear. Making an article featured should be simple, and articles should be listed chronologically.
3. Featured images are often cut off at the top or bottom, and one cannot use portrait images. Even images that should be "safe" are being cut off. See issue #347 as well. It's too difficult to get an image to fit in that box and without a featured image, the post looks empty.
<img width="622" alt="screen shot 2016-07-14 at 9 50 53 am" src="https://cloud.githubusercontent.com/assets/7093838/16842094/1e42f1f4-49aa-11e6-9bda-450dbc8c5d9e.png">

How can we fix this workflow so that it's easier to post? I've had fix and repost every post from the last few weeks.

**Comment by ageeroms** [comment]
Hello @little-wow , 

1. Only the most recently published post with Hero tag is displayed in the hero position, so I don't think there is an issue with multiple things being tagged as hero in future, i.e. when you add a new post and tag it as Hero, it bumps of the previous Hero out of that position. Yeah, a checkbox might be a better option. Please let me know if you'd like us to look into how to change that?
2. The 4 most recent items with "Featured" applied will be displayed below Hero on home/blog section. These items are featured on homepage and given larger display at top on blog listing to give them more emphasis. I think the order otherwise shown on blog is reverse chronological, so the most recent post first. This is what Ryan/Eric requested during discovery. If this is not the flow that you want, let's schedule a discussion so we can determine a more ideal workflow.
3. There is a design constraint here in that the same image that is used for Features/Heroes is used in the Related News section at the bottom of e.g. https://creativecommons.org/about/ -- so, the image needs to 3x2 aspect ratio. You can either crop prior to upload or use WordPress photo editing tools (https://codex.wordpress.org/Edit_Media) to ensure the image matches that ratio. Ideally, you should have an image for every post going forward, thought obviously that wasn't possible to go back and make all the old posts have images.

**Comment by ageeroms** [comment]
Please assign @fmann to look into how a checkbox might be a better option for assigning hilights.

**Comment by fmann** [comment]
I've issued a pull request for a change that makes the Highlights options checkboxes rather than an autocomplete field.

**Comment by little-wow** [comment]
So #354 and #360 are behaving in the way that we want them to.  What's the next step to push them live?

**Comment by ageeroms** [comment]
@mattl can you please deploy to production?
