### ISSUE TITLE
Link to a license flowchart in FAQ

### ISSUE THREAD

**Issue by soohyunpae** [creativecommons/creativecommons.org#400]
Go to https://creativecommons.org/faq/#choosing-a-license and search "flow chart" (see below). When you click on the link, it doesn't go anywhere and you only get a security message.

How should I decide which license to choose?
If you are unsure which license best suits your needs, there are plenty of resources to help rights holders choose the right CC license. CC Australia has developed a **flow chart** that may be useful in helping you settle on the right license for your work. Creative Commons has also compiled a list of examples that demonstrate how various licenses fit into licensors' overall strategies. You can also read case studies of others who are using CC licenses. The CC community can also respond to questions, and may have already addressed issues you raise. The CC community email discussion lists and discussion archives may be useful resources.

I think the easiest way to fix this is simply changing the link to the following:
http://creativecommons.org.au/content/licensing-flowchart.pdf

Thanks,
Soohyun

**Comment by little-wow** [comment]
@robmyers I can't change this page! thanks!

**Comment by robmyers** [comment]
@peterspdx where should this link go? Is the direct PDF link OK?

@little-wow it's in the FAQ repo: https://github.com/creativecommons/faq

The FAQ is maintained and deployed separately from the rest of the site. The other parts of the site for which this is true are /choose/ /licenses/ and the model platform.

For the FAQ and mp it's because they're complex documents maintained in an appropriate documentation format.

For /choose/ and /licenses/ it's because it's older code that runs in a different environment.

**Comment by mmoreshead** [comment]
@little-wow any of these weird FAQ ones that come up, feel free to assign them to me!

**Comment by mmoreshead** [comment]
fixed
