### ISSUE TITLE
Mailchimp issues with plugin

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#517]
These are the issues that were uncovered when testing the Mailchimp plugin.

1. The current implementation overwrites form fields whenever a record is updated. We really don't want this to happen so that we can filter on multiple attributes when we send emails to people. 
According to Gravity Form support, this plugin should be added to the theme functions.php file: https://www.gravityhelp.com/documentation/article/gform_mailchimp_override_empty_fields/

2. We want all information to be added to Mailchimp so that we can send emails to donors as well as people who want to be on our email lists.

3. Here are screenshots and explanations of the issues that were uncovered with testing surrounding paypal payment:

The transaction hits Mailchimp as soon as the "Pay with Paypal" button is pushed. Note – I did not check the "Yes, Subscribe me to the CC newsletter" in this test and I still got the email below.

<img width="903" alt="screen shot 2016-11-22 at 10 52 49 am" src="https://cloud.githubusercontent.com/assets/7093838/20689121/c0ddbaea-b591-11e6-8de3-4b1802df92d6.png">

<img width="879" alt="screen shot 2016-11-22 at 10 51 43 am" src="https://cloud.githubusercontent.com/assets/7093838/20689129/c7dc4f0a-b591-11e6-8636-b43d286cf4c0.png">

When the user clicks next here, nothing happens yet

<img width="857" alt="screen shot 2016-11-22 at 10 55 27 am" src="https://cloud.githubusercontent.com/assets/7093838/20689178/f8fb4906-b591-11e6-963c-8747aab2fe47.png">

I got the payment to go through via a fake card, and I got an email confirmation when it went through and I was redirected to the thank you page. (Found the fake card numbers here: https://stripe.com/docs/testing#cards) 

Paypal triggers the email, failed credit card does not.

4. Because we're adding everyone to the same list (which I do think is a good idea,) it means that donors who don't want to be added to the general mailing list will get the same "Thanks for signing up" double opt-in on the list, and I'm not sure how to make it so that they don't get that.
Maybe we could just auto-add people to the CC mailing list if they donate and take off the little check box on the address page? It's a double opt-in, and also send the donor onboarding emails triggered by the plugin.

**Comment by robinpuga** [comment]
@little-wow Our team will review and prepare the plugins for GravityForms / MailChimp integration. Thanks for the link to the additional plugin, hopefully that sorts out the issue of data being overwritten. 

Some clarification with respect to a couple items listed above: 

1) _"Note – I did not check the "Yes, Subscribe me to the CC newsletter" in this test and I still got the email below."_ 
NOTE that we can configure the GravityForms form to not send the record to MailChimp using its built-in conditional logic, however I think the _Thank You_ email you received is due to configuration on your MailChimp account...ie. It's sending a thank you email when you add people to the list. 

2) Re: double opt-in issue...there is a setting the GravityForms / MailChimp Integration plugin to remove double opt-in. More testing is necessary to confirm this user experience is what you are looking for. 

3) MOST IMPORTANTLY (and not mentioned in ticket above), if we do not do anything to confirm that PayPal transactions are legitimate in GravityForms then you will have a MailChimp list full of spam submissions. We will be pushing all the PayPal transactions that are submitted to GravityForms to MailChimp's list. 

4) One final thing to remember and test, if we are wishing to push all donation submission user records into MailChimp we need to ensure there is a field for "Receive Newsletter (Y/N)" or something like that in MailChimp. 

Please also note that we do not have access to your MailChimp account.
