### ISSUE TITLE
Donate Form PayPal Link on Mobile

### ISSUE THREAD

**Issue by robmyers** [creativecommons/creativecommons.org#556]
On /donate/#gf_3 in small mobile browsers the PayPal link overlaps the "Submit" button due to their respective positions:

![image](https://cloud.githubusercontent.com/assets/21746/21615244/890910ee-d191-11e6-894e-c756b1ed35d4.png)

I've changed this on live to prevent it but it doesn't look great. @ageeroms please can Affinity Bridge take a look at this?

**Comment by ageeroms** [comment]
Hi Rob, I've assigned to @altrugon. We'll follow up when we've had a chance to take a look.

**Comment by robmyers** [comment]
Thank you!

**Comment by altrugon** [comment]
I have replicated my previous solution on branch[ issue-556-paypal_link_overlap
](https://github.com/creativecommons/new-www-theme/compare/issue-556-paypal_link_overlap), please QA and merge into the code if everything looks good.

I have also closed ticket 463 because it's really outdated now, the branch associated with that ticket should be deleted.

**Comment by ageeroms** [comment]
Thanks very much. @robmyers there's a fix from Alberto, which should be applied.

**Comment by robmyers** [comment]
Tested, merged and deployed. It will show up soon.

Thank you!
