### ISSUE TITLE
Nag people to sign up for our email list?

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#567]
Heya @robmyers. Not enough people are signing up for our email list, so I would like to explore how we can bother them in a gentle, polite manner.

Would it be possible to put the following popup on the site using Mailchimp? Text is totally up for discussion, @ericsteuer is tagged for this reason. I can send you the code via email.

Thank you both!

<img width="911" alt="screen shot 2017-01-09 at 6 14 21 pm" src="https://cloud.githubusercontent.com/assets/7093838/21787523/b3f35516-d697-11e6-93aa-5f1d53aff3e2.png">

**Comment by robmyers** [comment]
We should talk to Affinity Bridge about this to make sure it maintains the site design.

@ageeroms , ping. :-)

Which pages/areas of the site would this be on? I'm wary of it clashing with funding and/or Global Summit signup promotion.

**Comment by little-wow** [comment]
Good question – maybe we should table this ticket until we decide on what the promo for the summit should look like? (That could also be a way to get people on the list.) Thanks!

**Comment by ericsteuer** [comment]
Good call @little-wow on maybe waiting until we think more about what summit promo should look like.

In the meantime, what do you all think -- just as an idea here -- of switching out the link out from the mail icon at the top right of the main nav bar across the site from one that creates a mailto: to one that links to our mailing list sign-up? The ability to email us is made plenty evident from the "Contact" link in the nav bar and it seems redundant to me to have that Contact link and then an email us link so close to each other. Also, since the other links in that top right space are social links, it makes more sense to me for the mail link to be one that brings you to a sign-up page for our email list.

To me, even though the mailing list sign-up flow is WAY better with the new site than it used to be, it's still a little hard to find. On the homepage, it's VERY easy to scroll right past it because there's so much else there.

**Comment by little-wow** [comment]
@ericsteuer I don't see why not – @robmyers any objections?

**Comment by robmyers** [comment]
I agree that having the icon be for the mailing list is more regular. It doesn't address the visibility issue, though.

The current mailing list sign-up on the front page is hidden away under the news items.

We could move it above the hero section, to go just under the top navigation.

Or we could treat this as a promotion and come up with a graphic and some text to replace "When we share, everyone wins" for a while.

"Stay tuned to the commons" may also not be the clearest call to action, even with the "email address" prompt in the text field. "Join our mailing list" is boring but clear, and explaining what people get may help persuade more people. (I'm not an expert at this though.)

We should talk to the web site's designers before changing anything like this.

**Comment by little-wow** [comment]
I'm not sure what the next steps here would be IRT working on this flow. I know it's not P1 for AB, so I don't want to put this on their plate, but I would like to examine the email flow and see how we can make it better.

There was some issue with changing the text under "Stay tuned to the commons" when I first started as well due to the size of the text and design constraints, so good call on talking to the designers, Rob.

@ericsteuer do you think that it would be worth scheduling a call to work on this, or should we table it.

**Comment by ericsteuer** [comment]
Agree on all this stuff. Language, placement, etc.

It should be pretty trivial to change, so let me ping AB and ask Anna to put it on the agenda for the next call I have with them.

**Comment by ageeroms** [comment]
Hello CC! 

Consider this topic added to our agenda for the 18th. Look forward to chatting with you then.

Best,
Anna

**Comment by little-wow** [comment]
yay! Thank you Anna!
