### ISSUE TITLE
Numbering and display problems in the Arabic translation files

### ISSUE THREAD

**Issue by georgehari** [creativecommons/creativecommons.org#570]
- It seems that there is a problem with the numbering of ordered lists in the Arabic translations:
http://cc4-ar-legalcode.legal.creativecommons.org/licenses/by-nd/4.0/legalcode.ar
etc.

- Also, in the footer, in the languages list, the order is ruined when resizing the browser (maybe it's related to the rtl reading order). 

I have to mention that they worked on older files when they updated the translation. I had to redo some formatting, so the staged files now should be the corrected ones. From now on, they were instructed to update the translation based on these staged files.

**Comment by hsawires** [comment]
Hi @georgehari

I was checking the files for the error, I think the order list in Arabic alphabet is not a CSS issue.
In the very last published version of the licenses I have included a .JS file called [arabic-ol.js] to fix the ordering in Arabic alphabet to fix the "ه" to be "ھ" and to order the list following the "Abjad Order" https://en.wikipedia.org/wiki/Abjad_numerals which is not the modern "hijāʼī" order which we couldn't  achieve with CSS only.

The [arabic-ol.js] file is replacing the modern order list "hijāʼī" with the "Abjad Order" list, and it could be found in the last published version. 
you can find the file in the following link
[arabic-ol.js](https://www.dropbox.com/s/abyfocfs6z5fg2i/arabic-ol.js?dl=0)
Just include it in the HTML's

For the footer I will check it and feed you back.

**Comment by georgehari** [comment]
Yes, the script arabic-ol.js is called in the files, please see https://github.com/creativecommons/creativecommons.org/commit/62d920298e63a73a045fd32187826debe347d123, but it's not to be found at https://creativecommons.org/includes/arabic-ol.js. So you may be right. 

@robmyers , if you place the script back in /includes/, it should solve the problem, right?

**Comment by robmyers** [comment]
https://creativecommons.org/includes/ is here:

https://github.com/creativecommons/new-creativecommons.org/tree/master/docroot/includes

But the version we use on legal-testing is here:

https://github.com/creativecommons/creativecommons.org/tree/master/docroot/includes

So for testing, we should use (and edit) the version in creativecommons.org , and the paths to files in these folders should be relative to the server root (e.g. <link rel="stylesheet" type="text/css" href="/includes/arabic-ol.css"> ).

We can then copy the required include files from the cc.org project to the new.cc.org org project before deploying both.

This is obviously a bad way of organizing the projects. :-( It's because the split between the Python and WordPress parts of the site was not completed properly.

**Comment by georgehari** [comment]
Thank you for the explanation! But I don't see **arabic-ol.js** in any of these URLs. Can you help us?

**Comment by peterspdx** [comment]
What do we need to finish this up so Mohammad can proof on staging?

**Comment by georgehari** [comment]
We just need to solve the numbering issue. I think there is nothing more for Mohammad to check.

**Comment by peterspdx** [comment]
Great. I do want Mohammad to have a final look after the numbering problem is solved, so that we have a sign off by our lead on the final files. Thanks so much for your help, George!

**Comment by georgehari** [comment]
@robmyers Can you help us with this?

**Comment by robmyers** [comment]
If you pull the version of cc4-ar-legalcode I have pushed, I updated the script paths to be relative to the root.

That will allow the files to find arabic-ol.js on the testing server.

**Comment by georgehari** [comment]
Great, thanks!
