### ISSUE TITLE
404 on French BY-NC-SA 4.0

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#625]
https://creativecommons.org/licenses/by-nc-sa/4.0/fr/

returns a 404. Mentioned on Twitter. https://twitter.com/ApolloLegacy01/status/872394477083799552

**Comment by robmyers** [comment]
@peterspdx @sarahpearson Is that a valid url for the 4.0 translations rather than the 3.0 (and earlier) ports? It's not in the wayback machine:

https://web.archive.org/web/*/creativecommons.org/licenses/by-nc-sa/4.0/fr/

A Google search shows about 744 hits for it.

https://www.google.ca/?gfe_rd=cr&ei=Viw4Wb34F-Pe8AfmzoRo#q=%22creativecommons.org/licenses/by-nc-sa/4.0/fr/%22&start=0

deed.fr works. I can redirect it to that or display that as /fr/ if that was what was happening and I broke it during the recent changes to the code made to protect that section of the site from attack.

**Comment by sarahpearson** [comment]
I should not be the definitive source on this, but it does not seem like it is a valid URL. The others have /deed before the language code, so I assume French should, too.

**Comment by peterspdx** [comment]
Valid URLs for translations of the 4.0 legal code are in this format:
https://creativecommons.org/licenses/by/4.0/legalcode.LA (where LA = language code)

While we don't have French 4.0 legal code yet published, it will go at:
https://creativecommons.org/licenses/by/4.0/legalcode.fr

So the link mentioned on twitter and 743 other places is wrong for two reasons: we don't have legal code in French (yet), and once we do it won't be there.

**Comment by gho87** [comment]
There is https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr which is what you were looking for. It works.

**Comment by robmyers** [comment]
Thank you @gho87 !

**Comment by robmyers** [comment]
I've added the License Link Problem tag as the information above is useful for that issue.
