### ISSUE TITLE
CC0 waiver: Shouldn't have to "read and understand" digital equivarent of fine print in a tiny box.

### ISSUE THREAD

**Issue by VortexCortex** [creativecommons/creativecommons.org#636]
https://creativecommons.org/choose/zero/waiver

Shot: https://files.catbox.moe/pljnql.png

Steps to reproduce the problem:

0. Think about using CC0 instead of MIT or BSD & actually try to do it.
1. Wind up on https://creativecommons.org/choose/zero/waiver after finding the tiny "we don't really want you to use the public domain tool" link.
2. Scroll down.
3. Look at that little box with Creative Commons Legal Code in it...
4. Try to read it like I'm supposed to agree to having done.
4. WTF!? (out loud)
5. Notice that it is ridiculously hard to read, like all the other shady legalese fine print that's deliberately difficult to understand.
6. Scroll the box with the scroll bar handle and watch it jump all over the place because scrollbar has to deal with such tiny box with so much crappy legalese in it.
7. Wonder why we can't just have nice things?
8. Think aloud, "Guess I'll just use BSD or MIT instead".
9. Realize all those other OSI licenses don't have "agree and continue" waivers (because it's not needed).

Note: Probably should have filed the bug against the legal team instead for being paranoid schizophrenics.  Seriously though, CC should think about patenting their invention of "digital fine print", could be quite "profitable".

**Comment by peterspdx** [comment]
The history to this is important, but I am going to bypass the bulk of it that because a lot has changed since we first launched CC0. When we did launch, CC believed that the "extra step" was important, out of an abundance of caution. We wanted (and continue to want) people to know what they're doing when they use CC0, same as our licenses. Bottom line is, we're going to be reconsidering this extra step, but not in this immediate moment. We'll definitely consult with the public when the time comes about changing this feature and your feedback will be important then. Thank you.
