### ISSUE TITLE
only PDF link to GNC charter? 

### ISSUE THREAD

**Issue by tvol** [creativecommons/creativecommons.org#702]
@claudioruiz i think https://creativecommons.org/network/charter/ should just have the text as HTML, not only PDF link or link to github page. what do you think?

**Comment by claudioruiz** [comment]
We discussed that with Diane and Rob. We have this page because it was important to legal to have one _canonical_ version of the Charter somewhere outside network.cc.org, considering we have the _source code_ on Github. 
And we thought the best way to keep that canonical is with a PDF like that. It won't be complicated to put also an HTML version there, but I thought it might be totally lost under the website. We can easily change that later on.
