### ISSUE TITLE
translation tool and language looks wonky

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#832]
the language chooser (translation tool) and accompanying language are appearing on pages flush to the left, when they should be on the right

https://creativecommons.org/licenses/by/4.0/
<img width="721" alt="screen shot 2018-07-09 at 12 28 58 pm" src="https://user-images.githubusercontent.com/8919762/42471737-b10c5976-8373-11e8-9242-e3dcf4002055.png">

**Comment by robmyers** [comment]
@robinpuga Is this some css I didn't merge?

**Comment by little-wow** [comment]
While we're here, the slider to the left has a weird scroll to it on my 18" screen

**Comment by robmyers** [comment]
@little-wow Eek! Which browser/version and can you grab a GIF of it?

**Comment by robinpuga** [comment]
Looking into it. Seems correct on our dev site: http://dev.cc.affinitybridge.com/licenses/by/4.0/ 
Will get back to you asap.

**Comment by robinpuga** [comment]
@robmyers We think it's related to the /includes/deed4.css file. On our server the file isn't minified and seems to be working. On the production server it looks like the file is minified https://creativecommons.org/includes/deed4.css 

Is it possible we missed a step in deployment?

**Comment by altrugon** [comment]
@little-wow The behaviour of the scroll is normal and necessary, the container of the slider has a maximum height of 70% of the viewport, in order to display all the content on not so tall screens we need the scrollbar, here is the piece of code that is doing that:

```
.slide-trigger {
  ...
  max-height: 70vh;
  overflow: auto;
```

What you are experiencing here is that you are watching the site on a wide screen with a narrow height, and unfortunately on your scenario you are just missing a few pixels to see the whole sliders.

**Comment by altrugon** [comment]
The language chooser (translation tool), is wrongly aligned because is missing CSS code, please take a look to the screen-shots below from dev and prod site:

![cc_-_dev](https://user-images.githubusercontent.com/398069/42496502-22f7725c-83db-11e8-8ce2-20c2408e9064.png)

![cc_-_prod](https://user-images.githubusercontent.com/398069/42496639-93edc560-83db-11e8-8852-c14be6b6615d.png)

**Comment by robmyers** [comment]
@robinpuga CloudFlare minifies our css, that is probably what you are seeing there.

**Comment by robmyers** [comment]
(Yes this can occasionally cause issues. :-) )

**Comment by robmyers** [comment]
@altrugon is this something the update script should have added, or have I missed a step or broken something? Should I just add style="text-align: right;" to any <div> of class language-selector-inner ?

**Comment by altrugon** [comment]
@robmyers you don't have to add any CSS code at all, all the CSS code you need is already in the repository since this is working on the dev site. The minify CSS is irrelevant as long as you keep the same order, but you are missing CSS code. Please make sure all the CSS code from deed4.css is on the production site.

**Comment by robmyers** [comment]
Fixed in new-creativecommons.org commit 7982bf2 .

You may need to thoroughly clear your browser cache for this to take effect.

@altrugon Thank you for diagnosing this and @ericsteuer thank you for reporting it!
