### ISSUE TITLE
RSS feed/open graph is borked

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#972]
Judging from this post and the below screenshots, something is broken in our metadata, or this post is broken, though I've done nothing different. It's impacting facebook posts and our RSS feeds, but not Twitter's card system. Link to broken post:
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fcreativecommons.org%2F2019%2F06%2F04%2Funesco-oer-recommendation-one-step-closer-to-adoption%2F

<img width="618" alt="Screen Shot 2019-06-04 at 9 39 52 AM" src="https://user-images.githubusercontent.com/7093838/58883629-cc347e80-86ac-11e9-8a7d-dcb68784f575.png">
<img width="481" alt="Screen Shot 2019-06-04 at 9 39 19 AM" src="https://user-images.githubusercontent.com/7093838/58883630-cc347e80-86ac-11e9-9094-8c99fab516f5.png">

<img width="885" alt="Screen Shot 2019-06-04 at 9 40 50 AM" src="https://user-images.githubusercontent.com/7093838/58883659-de162180-86ac-11e9-8339-0c5bb1ef11ee.png">

I wonder if this is caused by our Yoast SEO and WP instance not being the most up to date? I can update if it's not going to break the site. Thoughts?

**Comment by hugosolar** [comment]
Fixed
The problem was related to the featured image dimensions (2867x2086 px)
it seems that the SEO plugin dismissed it because it was too large.
I upload a smaller version of the image and attached it to the facebook tab in the Yoas SEO metabox

![Screen Shot 2019-06-05 at 2 35 21 PM](https://user-images.githubusercontent.com/894708/58980838-2b72bb80-879f-11e9-8634-72b944b3bf73.png)
